name: Frontend Build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'magneer/food_manager'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Run build script
        run: |
          chmod +x ./food_manager/remote_build.sh
          ./food_manager/remote_build.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update frontend build
          commit_user_name: MagneeR [GitHub Actions]
          commit_user_email: magneer47@gmail.com
          commit_author: MagneeR <magneer47@gmail.com>
